#!/usr/bin/env python
"""sc-gitlab-webhook - The Gitlab webhook to receive and process Gitlab events

Copyright (c) 2021 Scott Lau
"""
# NOTE: This binary is provided for convenience.  It is nice to be able to run
# the checks from the repository.  This is not included on the releases.  We
# are using entry_points mechanism on the setup.py.

from sys import exit

from webhook.main import main

exit(main())
